---
title: "hw-03"
author: "Your Name (S000000)"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(scales)
```

### Exercise 1

```{r hw2-ex1}
# remove this comment and add the code for Exercise 1 here

```


_Remove this text, and add your answer for Exercise 1 here._

### Exercise 2

```{r hw2-ex2}
# remove this comment and add the code for Exercise 2 here

```


_Remove this text, and add your answer for Exercise 2 here._

### Exercise 3

```{r hw2-ex3}
# remove this comment and add the code for Exercise 3 here

```


_Remove this text, and add your answer for Exercise 3 here._

### Exercise 4

```{r hw2-ex4}
# remove this comment and add the code for Exercise 4 here

```


_Remove this text, and add your answer for Exercise 4 here._

### Exercise 5

```{r hw2-ex5}
# remove this comment and add the code for Exercise 5 here

```


_Remove this text, and add your answer for Exercise 5 here._

